#ifndef __TYPES_H__
#define __TYPES_H__

typedef char _bool;

#define MAP_WIDTH 200
#define MAP_HEIGHT 200


#define PREDATOR_INIT_CNT 300
#define PREY_INIT_CNT 3000


#define PREDATOR_BABY_DELAY -200
#define PREDATOR_MARRY_DELAY -400
#define PREDATOR_MARRY_PUNISHMENT 500

#define PREDATOR_LIFE_SPAN 700
#define PREDATOR_SIGHT 5

#define PREDATOR_HEREDITY_SEED 6
#define PREDATOR_MUTATION_SEED 30
#define PREDATOR_ODD_HEREDITY_SEED 50

#define PREDATOR_GENE_STORE_SIZE 50

#define PREDATOR_PROBABILITY_SEED 1000
#define PREDATOR_MUTATION_PROBABILITY 10 /* PROBABILITY/SEED */
#define PREDATOR_ODD_HEREDITY_PROBABILITY 1 /* PROBABILITY/SEED */


#define DIRECT_CNT 4
#define DIRECT_UP 0
#define DIRECT_DOWN 1
#define DIRECT_LEFT 2
#define DIRECT_RIGHT 3


#define CODE_BLANK 0
#define CODE_PREDAT0R 1
#define CODE_PREY 2

#endif